### PR TITLE
Reformatting of the README, moving the shebangs to the top of the shell scripts, and removing trailing whitespace

### PR DESCRIPTION
**Pull request by 06kellyjac**
Nice project Dylan. I've done a bit of cleaning up on the `README.md` and moved the shebangs just to be safe.

### CODE REVIEW

**Comment by DylanHamer** [comment]
Thank you! I haven't been able to work on the project since I broke my
kindle. I'll merge this as soon as I get a chance!

**Comment by 06kellyjac** [comment]
Yeah that's a shame, I saw you mention that it broke on the Reddit post. There's no rush on the merge 😄

**Comment by DylanHamer** [comment]
Shit, sorry I forgot about the merge.

**Comment by DylanHamer** [comment]
Alright, that's merged now. Thanks!

**Pull request merged**
